/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import com.user.login;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author navad
 */
public class secCmarr extends javax.swing.JFrame {

    /**
     * Creates new form entermarks
     */
    public String examname ;
    public String examsub;
    public String a1;
    public String a2;
    public String a3;
    public String a4;
    public String a5;
    public String a6;
    public String a7;
    public String a8;
    public String a9;
    public String a10;

    public secCmarr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel9.setText("Subject");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton2.setText("Mark Attendence");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton3.setText("Enter Marks");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton4.setText("Student Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel8.setText("Section");

        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sec C", "Sec A", "Sec B", "Sec D" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(153, 153, 255));
        jLabel23.setText("211FA04060");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel24.setText("211FA04062");

        jLabel25.setText("211FA04063");

        jLabel26.setText("211FA04064");

        jLabel27.setText("211FA04066");

        jLabel28.setText("211FA04065");

        jLabel29.setText("211FA04067");

        jLabel30.setText("211FA04069");

        jLabel31.setText("211FA04068");

        jLabel32.setBackground(new java.awt.Color(153, 153, 255));
        jLabel32.setText("211FA04061");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel10.setText("Exam name");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NA", "WT-1", "WT-2", "MID-1" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel33.setText("Subject");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NA", "oops", "ds", "dbms" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Emp_no:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("101");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Emp_name:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("Dep_name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("CSE");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel6.setText("varun");

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setText("Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        studentdetails sd = new studentdetails();
        sd.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        markattendence ma = new markattendence();
        ma.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        a1=jTextField13.getText();
        a2=jTextField14.getText();
        a3=jTextField16.getText();
        a4=jTextField15.getText();
        a5=jTextField18.getText();
        a6=jTextField17.getText();
        a7=jTextField19.getText();
        a8=jTextField20.getText();
        a9=jTextField21.getText();
        a10=jTextField22.getText();
        if (examname == "WT1" && examsub == "oops"){
        try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set jwt1 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set jwt1 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set jwt1 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set jwt1 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set jwt1 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set jwt1 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set jwt1 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set jwt1 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set jwt1 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set jwt1 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
    }
        else if (examname == "WT2" && examsub == "oops"){
            try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set jwt2 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set jwt2 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set jwt2 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set jwt2 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set jwt2 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set jwt2 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set jwt2 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set jwt2 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set jwt2 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set jwt2 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
        }
        else if (examname == "mid1" && examsub == "oops"){
            try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set jmid1 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set jmid1 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set jmid1 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set jmid1 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set jmid1 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set jmid1 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set jmid1 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set jmid1 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set jmid1 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set jmid1 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
        }
        else if (examname == "WT1" && examsub == "ds"){
        try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set dswt1 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set dswt1 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set dswt1 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set dswt1 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set dswt1 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set dswt1 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set dswt1 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set dswt1 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set dswt1 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set dswt1 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
    }
        else if (examname == "WT2" && examsub == "ds"){
            try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set dswt2 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set dswt2 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set dswt2 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set dswt2 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set dswt2 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set dswt2 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set dswt2 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set dswt2 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set dswt2 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set dswt2 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
        }
        else if (examname == "mid1" && examsub == "ds"){
            try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set dsmid1 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set dsmid1 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set dsmid1 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set dsmid1 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set dsmid1 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set dsmid1 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set dsmid1 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set dsmid1 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set dsmid1 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set dsmid1 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
        }
        else if (examname == "WT1" && examsub == "dbms"){
        try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set dbmswt1 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set dbmswt1 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set dbmswt1 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set dbmswt1 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set dbmswt1 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set dbmswt1 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set dbmswt1 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set dbmswt1 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set dbmswt1 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set dbmswt1 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
    }
        else if (examname == "WT2" && examsub == "dbms"){
            try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set dbmswt2 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set dbmswt2 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set dbmswt2 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set dbmswt2 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set dbmswt2 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set dbmswt2 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set dbmswt2 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set dbmswt2 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set dbmswt2 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set dbmswt2 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
        }
        else if (examname == "mid1" && examsub == "dbms"){
            try
        {

            Class. forName ("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/attendance","root","nani123");
            Statement stmt = con.createStatement();
            String c1 = "update  secCmar set dbmsmid1 = '"+(a1)+"' where id = '211FA06060' ";
            String c2 = "update  secCmar set dbmsmid1 = '"+(a2)+"' where id = '211FA06061' ";
            String c3 = "update  secCmar set dbmsmid1 = '"+(a3)+"' where id = '211FA06062' ";
            String c4 = "update  secCmar set dbmsmid1 = '"+(a4)+"' where id = '211FA06063' ";
            String c5 = "update  secCmar set dbmsmid1 = '"+(a5)+"' where id = '211FA06064' ";
            String c6 = "update  secCmar set dbmsmid1 = '"+(a6)+"' where id = '211FA06065' ";
            String c7 = "update  secCmar set dbmsmid1 = '"+(a7)+"' where id = '211FA06066' ";
            String c8 = "update  secCmar set dbmsmid1 = '"+(a8)+"' where id = '211FA06067' ";
            String c9 = "update  secCmar set dbmsmid1 = '"+(a9)+"' where id = '211FA06068' ";
            String c10 = "update  secCmar set dbmsmid1 = '"+(a10)+"' where id = '211FA06069' ";
            stmt.executeUpdate(c1);
            stmt.executeUpdate(c2);
            stmt.executeUpdate(c3);
            stmt.executeUpdate(c4);
            stmt.executeUpdate(c5);
            stmt.executeUpdate(c6);
            stmt.executeUpdate(c7);
            stmt.executeUpdate(c8);
            stmt.executeUpdate(c9);
            stmt.executeUpdate(c10);
            JOptionPane.showMessageDialog(null,"Successfully Updated");

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());
        }
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int a =  jComboBox1.getSelectedIndex();
        if (a==1){
            secAmarr c = new secAmarr();
            c.show();
            dispose();
        }
        if (a==2){
            secBmarr d = new secBmarr();
            d.show();
            dispose();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        int a =  jComboBox2.getSelectedIndex();
        if(a==1)
            examname = "WT1";
        if(a==2)
            examname = "WT2";
        if(a==3)
            examname = "mid1";
        
            
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        int a =  jComboBox3.getSelectedIndex();
        if(a==1)
            examsub = "oops";
        if(a==2)
            examsub = "ds";
        if(a==3)
            examsub = "dbms";
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secCmarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secCmarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secCmarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secCmarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secCmarr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    // End of variables declaration//GEN-END:variables
}
